### ISSUE TITLE
Change has-env to flag

### ISSUE THREAD

**Issue by examosa** [bahmutov/print-env#21]
## Feature request

Rather than 2 bin files, the cli should be condensed into a single bin, with has-env being a flag of print-env. I propose a `-e|--exists` flag on print-env to replace has-env. The latter will be deprecated, with a removal in a future release (**BREAKING CHANGE**).

### Current behavior
```sh
$ print-env TRAVIS NODE
NODE_ENV=development
TRAVIS_BRANCH=master
...
$ has-env GH
Found environment variables:
GH_API_KEY
GH_INSTALLATION_ID
...
```
### Desired behavior
```sh
$ print-env TRAVIS NODE
NODE_ENV=development
TRAVIS_BRANCH=master
...
$ print-env -e GH
Found environment variables:
GH_API_KEY
GH_INSTALLATION_ID
...
```

**Comment by bahmutov** [comment]
hmm, interesting, I like it. It would be a breaking change so the final squashed commit from pull request needs to follow this convention https://github.com/semantic-release/semantic-release#commit-message-format
