### ISSUE TITLE
How to use print-env vs has-env when running via npx

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/print-env#6]
If we don't want to install first, can we say
```
npx @bahmutov/print-env GOO
```

and print variables that start with `GOO`? Right now it switches to `has-env` automatically and just prints
```
GOO1: true
```

work-around for now
```
npm install @bahmutov/print-env
npx print-env GOO
```

**Comment by examosa** [comment]
Just use the -p|--package option:
```
npx -p @bahmutov/print-env print-env GOO
```

**Comment by bahmutov** [comment]
Thank you @Teomik129 that solves it, I have added this to the README
